version: "3"
services:
  shici:
    build: .
    restart: always
    labels:
      - traefik.http.routers.next-app.rule=Host(`https://www.ru1234.com`)
      - traefik.http.routers.next-app.tls=true
      - traefik.http.routers.next-app.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
